name: nhc
summary: LBNL Node Health Check (NHC)
description: |
  LBNL Node Health Check (NHC)

adopt-info: nhc

base: core18

grade: stable
confinement: strict

apps:
  nhc:
    command: bin/nhc

parts:
  nhc:
    plugin: dump
    source: https://github.com/mej/nhc.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-packages:
      - automake
      - make
    stage:
      - usr/
      - nhc.conf
    prime:
      - usr/
      - nhc.conf
    override-build: |
      snapcraftctl build
      ./autogen.sh
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr
      make
      make install
      snapcraftctl set-version `git rev-parse --short HEAD`

  nhc-bin:
    plugin: dump
    source: src/nhc/
    source-type: local

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/
