name: nhc
summary: LBNL Node Health Check (NHC)
description: |
  LBNL Node Health Check (NHC)

adopt-info: nhc

base: core20

grade: stable
confinement: classic

apps:
  nhc:
    command: bin/nhc

parts:
  nhc:
    plugin: dump
    source: https://github.com/omnivector-solutions/nhc.git
    source-tag: 1.4.2-omni
    source-depth: 1
    build-packages:
      - automake
      - make
    stage:
      - usr/
    prime:
      - usr/
    override-build: |
      snapcraftctl build
      ./autogen.sh
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr --libexecdir=$SNAPCRAFT_PART_INSTALL/usr/lib
      make
      make install
      # Set snap version
      snapcraftctl set-version `git describe --tags`

  nhc-vars:
    plugin: dump
    source: src/nhc-vars/
    source-type: local

  nhc-bin:
    plugin: dump
    source: src/nhc/
    source-type: local

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/
